# Generated by Django 2.2.2 on 2019-09-23 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billing_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=120)),
                ('bil_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=120)),
                ('bil_zip', models.IntegerField(default=1215)),
            ],
        ),
    ]
