# Generated by Django 2.2.2 on 2019-10-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_address', '0002_auto_20191004_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_profile',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
