# Generated by Django 2.2.2 on 2019-11-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_address', '0003_auto_20191005_0008'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_profile',
            name='nid',
            field=models.IntegerField(default='543', verbose_name='NID no'),
        ),
    ]
