# Generated by Django 2.2.2 on 2019-11-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_address', '0004_billing_profile_nid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_profile',
            name='nid',
            field=models.BigIntegerField(default='543', verbose_name='NID no'),
        ),
    ]
