# Generated by Django 2.2.2 on 2019-09-22 15:03

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='day',
        ),
        migrations.AddField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 27, 21, 3, 9, 895945), null=True),
        ),
        migrations.AddField(
            model_name='product_price',
            name='product_title',
            field=models.ForeignKey(blank=True, null=True, on_delete='DO_NOTHING', to='browser.Product'),
        ),
        migrations.AddField(
            model_name='product_price',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product_price',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
