# Generated by Django 2.2.2 on 2019-09-23 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0003_auto_20190923_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 28, 22, 1, 50, 407784), null=True),
        ),
    ]
