# Generated by Django 2.2.2 on 2019-09-26 16:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0005_auto_20190926_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_category',
            field=models.ForeignKey(blank=True, null=True, on_delete='DO_NOTHING', to='browser.Category_post'),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 1, 22, 48, 41, 871197), null=True),
        ),
    ]
