# Generated by Django 2.2.2 on 2019-09-26 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0006_auto_20190926_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 1, 22, 53, 35, 950842), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_category',
            field=models.ForeignKey(blank=True, null=True, on_delete='DO_NOTHING', to='browser.Category_post', verbose_name='Category'),
        ),
    ]
