# Generated by Django 2.2.2 on 2019-09-26 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0007_auto_20190926_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_post',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 2, 0, 1, 43, 599001), null=True),
        ),
    ]
