# Generated by Django 2.2.2 on 2019-09-30 14:45

import browser.models
import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0010_auto_20190930_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 5, 20, 45, 32, 14022), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=browser.models.upload_image_path, verbose_name='Image'),
            preserve_default=False,
        ),
    ]
