# Generated by Django 2.2.2 on 2019-10-04 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0014_auto_20191002_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 9, 21, 44, 53, 925929), null=True),
        ),
    ]
