# Generated by Django 2.2.2 on 2019-10-04 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0016_auto_20191004_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 9, 21, 48, 11, 367571), null=True),
        ),
    ]
