# Generated by Django 2.2.2 on 2019-10-04 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0018_auto_20191004_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 10, 0, 8, 55, 148031), null=True),
        ),
    ]
