# Generated by Django 2.2.2 on 2019-10-07 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0026_auto_20191007_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 12, 16, 4, 16, 414111), null=True),
        ),
    ]
