# Generated by Django 2.2.2 on 2019-10-07 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0027_auto_20191007_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 12, 19, 41, 18, 245491), null=True),
        ),
    ]
