# Generated by Django 2.2.2 on 2019-10-07 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0030_auto_20191007_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 12, 22, 33, 13, 692071), null=True),
        ),
    ]
