# Generated by Django 2.2.2 on 2019-10-08 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0032_auto_20191008_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 13, 6, 6, 20, 125276), null=True),
        ),
    ]
