# Generated by Django 2.2.2 on 2019-10-09 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0034_auto_20191010_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 15, 0, 12, 7, 302788), null=True),
        ),
    ]
