# Generated by Django 2.2.2 on 2019-10-09 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0035_auto_20191010_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 15, 0, 13, 58, 499964), null=True),
        ),
    ]
