# Generated by Django 2.2.2 on 2019-10-17 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0036_auto_20191010_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 23, 3, 15, 51, 569336), null=True),
        ),
    ]
