# Generated by Django 2.2.2 on 2019-10-17 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0039_auto_20191018_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 23, 5, 14, 43, 619920), null=True),
        ),
    ]
