# Generated by Django 2.2.2 on 2019-10-18 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0043_auto_20191018_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 23, 6, 6, 20, 976028), null=True),
        ),
    ]
