# Generated by Django 2.2.2 on 2019-10-19 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0045_auto_20191019_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 24, 8, 11, 13, 262067), null=True),
        ),
    ]
