# Generated by Django 2.2.2 on 2019-10-19 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0046_auto_20191019_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 24, 8, 46, 38, 691114), null=True),
        ),
    ]
