# Generated by Django 2.2.2 on 2019-10-20 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0049_auto_20191020_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 25, 23, 39, 35, 846), null=True),
        ),
    ]
