# Generated by Django 2.2.2 on 2019-10-21 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0056_auto_20191020_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 26, 21, 8, 43, 168189), null=True),
        ),
    ]
