# Generated by Django 2.2.2 on 2019-10-30 21:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0061_auto_20191021_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 5, 3, 45, 20, 907201), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_category',
            field=models.ForeignKey(on_delete='DO_NOTHING', to='browser.Category_post', verbose_name='Category'),
        ),
    ]
