# Generated by Django 2.2.2 on 2019-11-03 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0062_auto_20191031_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 8, 16, 50, 9, 152543), null=True),
        ),
    ]
