# Generated by Django 2.2.2 on 2019-11-05 19:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0063_auto_20191103_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 11, 1, 48, 56, 692507), null=True),
        ),
    ]
