# Generated by Django 2.2.2 on 2019-10-07 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('live_auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlive',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=33.33, max_digits=10),
        ),
        migrations.AddField(
            model_name='productlive',
            name='day',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productlive',
            name='price',
            field=models.DecimalField(decimal_places=2, default=33.33, max_digits=10, verbose_name='Market Price'),
        ),
        migrations.AddField(
            model_name='productlive',
            name='stating_price',
            field=models.DecimalField(decimal_places=2, default=33.33, max_digits=10, verbose_name='Starter Price'),
        ),
        migrations.CreateModel(
            name='Product_price_live',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product_title', models.ForeignKey(blank=True, null=True, on_delete='DO_NOTHING', to='live_auction.ProductLive')),
                ('user', models.ForeignKey(blank=True, default=1, null=True, on_delete='DO_NOTHING', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
