# Generated by Django 2.2.2 on 2019-10-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_auction', '0002_auto_20191007_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlive',
            name='day',
        ),
    ]
