# Generated by Django 2.2.2 on 2019-10-07 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live_auction', '0003_remove_productlive_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlive',
            name='p_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='browser.Category_post', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='productlive',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
