# Generated by Django 2.2.2 on 2019-10-07 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live_auction', '0004_auto_20191007_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_price_live',
            name='product_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='live_auction.ProductLive'),
        ),
        migrations.AlterField(
            model_name='product_price_live',
            name='user',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
