# Generated by Django 2.2.2 on 2019-10-07 21:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('live_auction', '0006_productlive_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlive',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 9, 3, 4, 40, 640173), null=True),
        ),
        migrations.CreateModel(
            name='Live_second_timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('live', models.BooleanField(default=False)),
                ('end_timer', models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 8, 3, 5, 40, 641174), null=True)),
                ('live_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='live_auction.ProductLive')),
            ],
        ),
    ]
