# Generated by Django 2.2.2 on 2019-10-19 02:46

import datetime
from django.db import migrations, models
import live_auction.models


class Migration(migrations.Migration):

    dependencies = [
        ('live_auction', '0021_auto_20191019_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlive',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=live_auction.models.upload_image_path, verbose_name='Image_2'),
        ),
        migrations.AddField(
            model_name='productlive',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=live_auction.models.upload_image_path, verbose_name='Image_3'),
        ),
        migrations.AddField(
            model_name='productlive',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=live_auction.models.upload_image_path, verbose_name='Image_4'),
        ),
        migrations.AlterField(
            model_name='live_second_timer',
            name='end_timer',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 19, 8, 51, 38, 700638), null=True),
        ),
        migrations.AlterField(
            model_name='productlive',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 10, 20, 8, 46, 38, 698622), null=True),
        ),
        migrations.AlterField(
            model_name='productlive',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=live_auction.models.upload_image_path, verbose_name='Image_1'),
        ),
    ]
