# Generated by Django 2.2.2 on 2019-10-05 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('browser', '0021_auto_20191005_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckouSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=14)),
                ('zip_c', models.IntegerField(max_length=4)),
                ('card_name', models.CharField(max_length=120)),
                ('card_no', models.IntegerField(max_length=20)),
                ('active', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('p_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.Product', verbose_name='Product Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
