# Generated by Django 2.2.2 on 2019-10-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkousystem',
            name='user',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
