# Generated by Django 2.2.2 on 2019-10-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20191005_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkousystem',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
