# Generated by Django 2.2.2 on 2019-10-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20191005_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkousystem',
            name='card_no',
            field=models.IntegerField(),
        ),
    ]
