# Generated by Django 2.2.2 on 2019-10-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_auto_20191018_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkousystem',
            name='card_no',
            field=models.IntegerField(max_length=20),
        ),
    ]
