# Generated by Django 2.2.2 on 2019-10-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_auto_20191018_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkousystem',
            name='zip_c',
            field=models.IntegerField(),
        ),
    ]
