# Generated by Django 2.2.2 on 2019-10-17 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_admin',
            name='user',
        ),
    ]
