# Generated by Django 2.2.2 on 2019-10-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0002_remove_contact_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_admin',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
