# Generated by Django 2.2.2 on 2019-10-17 23:13

from django.db import migrations, models
import nilam_custom.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nilam_slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, editable=False, unique=True)),
                ('description', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to=nilam_custom.models.upload_image_path, verbose_name='Image')),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
