# Generated by Django 2.2.2 on 2019-10-18 00:06

from django.db import migrations, models
import nilam_custom.models


class Migration(migrations.Migration):

    dependencies = [
        ('nilam_custom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nilam_footer_section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('image', models.ImageField(upload_to=nilam_custom.models.upload_image_path, verbose_name='Image')),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nilam_info_section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('image', models.ImageField(upload_to=nilam_custom.models.upload_image_path, verbose_name='Image')),
                ('active', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
