# Generated by Django 2.2.2 on 2019-10-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nilam_custom', '0003_nilam_live_rule_nilam_regular_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilam_live_rule',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='nilam_regular_rule',
            name='description',
            field=models.TextField(),
        ),
    ]
